spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true // sout?? ???? ????
        format_sql: true
        use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug # logger ? ??
  org.hibernate.type: trace
